import type { TestRunResult, IssueSummary } from '../agents/runner.js';

// ---------------------------------------------------------------------------
// Markdown report generator (spec §8.1)
// ---------------------------------------------------------------------------

/**
 * Generate a Markdown summary report from test run results and filed issues.
 *
 * The report includes:
 * - Summary counts (total, passed, failed, flaky, skipped)
 * - New Issues table
 * - Flaky Tests table
 * - Fix Status table (placeholder for when fix data is available)
 *
 * @param results - The aggregated test run results.
 * @param issues - Issues filed during this run.
 * @param fixStatuses - Optional fix branch statuses for the Fix Status table.
 * @returns The Markdown string.
 */
export function generateMarkdownReport(
  results: TestRunResult,
  issues: IssueSummary[],
  fixStatuses?: Array<{
    issueNumber: number;
    branch: string;
    testResult: 'PASS' | 'FAIL' | 'PENDING';
    regressionCount: number | null;
  }>,
): string {
  const date = results.completedAt
    ? new Date(results.completedAt).toISOString().split('T')[0]
    : new Date().toISOString().split('T')[0];

  const passRate = results.total > 0
    ? Math.round((results.passed / results.total) * 100)
    : 0;
  const failRate = results.total > 0
    ? Math.round((results.failed / results.total) * 100)
    : 0;
  const flakyRate = results.total > 0
    ? Math.round((results.flaky / results.total) * 100)
    : 0;

  const lines: string[] = [];

  // -------------------------------------------------------------------------
  // Header
  // -------------------------------------------------------------------------

  lines.push(`# QA Agent Test Report — ${date}`);
  lines.push('');

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------

  lines.push('## Summary');
  lines.push(`- **Total scenarios:** ${results.total}`);
  lines.push(`- **Passed:** ${results.passed} (${passRate}%)`);
  lines.push(`- **Failed:** ${results.failed} (${failRate}%)`);
  lines.push(`- **Flaky:** ${results.flaky} (${flakyRate}%)`);
  lines.push(`- **Skipped:** ${results.skipped}`);
  lines.push('');

  // -------------------------------------------------------------------------
  // New Issues Created
  // -------------------------------------------------------------------------

  const bugs = issues.filter((i) => !isFlakyIssue(i));

  if (bugs.length > 0) {
    lines.push(`## New Issues Created: ${bugs.length}`);
    lines.push('| Issue | Test ID | Area | Priority | Title |');
    lines.push('|-------|---------|------|----------|-------|');
    for (const issue of bugs) {
      lines.push(
        `| #${issue.issueNumber} | ${issue.testId} | ${issue.area} | ${issue.priority} | ${issue.title} |`,
      );
    }
    lines.push('');
  } else {
    lines.push('## New Issues Created: 0');
    lines.push('');
    lines.push('No new bugs discovered.');
    lines.push('');
  }

  // -------------------------------------------------------------------------
  // Flaky Tests
  // -------------------------------------------------------------------------

  const flakyIssues = issues.filter(isFlakyIssue);

  if (flakyIssues.length > 0 || results.flaky > 0) {
    lines.push(`## Flaky Tests: ${results.flaky}`);
    lines.push('| Test ID | Area | Pass Rate | Notes |');
    lines.push('|---------|------|-----------|-------|');
    for (const issue of flakyIssues) {
      lines.push(
        `| ${issue.testId} | ${issue.area} | intermittent | Filed as #${issue.issueNumber} |`,
      );
    }
    lines.push('');
  }

  // -------------------------------------------------------------------------
  // Fix Status
  // -------------------------------------------------------------------------

  if (fixStatuses && fixStatuses.length > 0) {
    lines.push('## Fix Status');
    lines.push('| Issue | Branch | Test Result | Regression Check |');
    lines.push('|-------|--------|-------------|------------------|');
    for (const fix of fixStatuses) {
      const regressionText = fix.regressionCount === null
        ? '—'
        : `${fix.regressionCount} regressions`;
      lines.push(
        `| #${fix.issueNumber} | ${fix.branch} | ${fix.testResult} | ${regressionText} |`,
      );
    }
    lines.push('');
  }

  // -------------------------------------------------------------------------
  // Footer
  // -------------------------------------------------------------------------

  lines.push('---');
  lines.push(`*Generated by QA Agent at ${results.completedAt ?? new Date().toISOString()}*`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Check if an issue is flaky based on its priority (flaky issues are
 * typically filed as P3).
 */
function isFlakyIssue(issue: IssueSummary): boolean {
  return issue.priority === 'P3';
}
